version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint test
          command: npm run lint
      # This is where we should add test
  deploy-prod:
    docker:
      - image: circleci/node:10.5.0
    steps:
      - run:
          name: Semantic Release
          command: npm run semantic-release

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master